'use client';
import { useEffect, useMemo, useState } from 'react';
import { createCheckoutOrder } from './actions/checkout';
import { createBrowserSupabaseClient } from '@/lib/supabase-browser';
import type { FormEvent } from 'react';
import { Search, ShoppingBasket, MapPin, Plus, Minus, X, ArrowRight, Leaf, Clock3, ShieldCheck, Truck, CheckCircle2, ChevronDown, Heart, Menu } from 'lucide-react';

type Product = { id:string; slug:string; name:string; unit:string; price:number; oldPrice?:number; category:string; emoji:string; color:string; tag?:string; desc:string; imageUrl?:string|null; isSpecial?:boolean; stockQty?:number; inStock?:boolean };
type CartItem = Product & { quantity:number };
const PRODUCTS:Product[] = [
 {id:'p1',slug:'fresh-banana-bunch',name:'Fresh Banana Bunch',unit:'per bunch',price:24.99,category:'Fruit & Veg',emoji:'🍌',color:'#fff4cf',tag:'Local favourite',desc:'Naturally sweet and ready to enjoy.'},
 {id:'p2',slug:'farm-fresh-tomatoes',name:'Farm Fresh Tomatoes',unit:'1 kg',price:29.99,oldPrice:34.99,category:'Fruit & Veg',emoji:'🍅',color:'#ffe7df',tag:'Save 15%',desc:'Juicy tomatoes for salads and cooking.'},
 {id:'p3',slug:'avocados',name:'Avocados',unit:'pack of 3',price:32.50,category:'Fruit & Veg',emoji:'🥑',color:'#e8f3d9',desc:'Creamy, ripe and full of goodness.'},
 {id:'p4',slug:'baby-spinach',name:'Baby Spinach',unit:'200 g bag',price:18.99,category:'Fruit & Veg',emoji:'🥬',color:'#e2f1df',desc:'Tender leafy greens, washed and ready.'},
 {id:'p5',slug:'free-range-eggs',name:'Free Range Eggs',unit:'6 pack',price:26.99,category:'Dairy & Eggs',emoji:'🥚',color:'#f5eddf',tag:'Farm fresh',desc:'A breakfast essential from happy hens.'},
 {id:'p6',slug:'fresh-full-cream-milk',name:'Fresh Full Cream Milk',unit:'2 litre',price:34.99,category:'Dairy & Eggs',emoji:'🥛',color:'#e6f2fa',desc:'Creamy everyday dairy goodness.'},
 {id:'p7',slug:'sourdough-loaf',name:'Sourdough Loaf',unit:'1 loaf',price:39.99,category:'Bakery',emoji:'🍞',color:'#f5e6d1',desc:'Crusty outside, soft and airy inside.'},
 {id:'p8',slug:'sunday-7-colours-box',name:'Sunday 7-Colours Box',unit:'family combo',price:199.00,oldPrice:229,category:'Produce Boxes',emoji:'🧺',color:'#e7f2dd',tag:'Family favourite',desc:'Potatoes, carrots, beetroot, pumpkin and cabbage.'},
 {id:'p9',slug:'weekly-family-starter-pack',name:'Weekly Family Starter Pack',unit:'value combo',price:149.00,category:'Produce Boxes',emoji:'🥕',color:'#ffeadb',desc:'Everyday produce to get your week started.'},
 {id:'p10',slug:'long-grain-rice',name:'Long Grain Rice',unit:'2 kg bag',price:42.99,category:'Pantry',emoji:'🍚',color:'#f5f0df',desc:'A pantry staple for family meals.'},
 {id:'p11',slug:'creamy-peanut-butter',name:'Creamy Peanut Butter',unit:'400 g jar',price:36.99,category:'Pantry',emoji:'🥜',color:'#f4e4d2',desc:'Smooth, rich and perfect on toast.'},
 {id:'p12',slug:'fresh-orange-bag',name:'Fresh Orange Bag',unit:'2 kg bag',price:39.99,category:'Fruit & Veg',emoji:'🍊',color:'#ffebd2',desc:'Bright, juicy citrus picked for flavour.'}
];
const CATEGORIES = [{name:'All groceries',emoji:'🛒'},{name:'Fruit & Veg',emoji:'🥑'},{name:'Dairy & Eggs',emoji:'🥛'},{name:'Bakery',emoji:'🥖'},{name:'Pantry',emoji:'🫙'},{name:'Produce Boxes',emoji:'🧺'}];
const money=(n:number)=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(n);
export default function Home(){
 const [products,setProducts]=useState<Product[]>(PRODUCTS); const [cart,setCart]=useState<CartItem[]>([]); const [hydrated,setHydrated]=useState(false); const [query,setQuery]=useState(''); const [category,setCategory]=useState('All groceries'); const [cartOpen,setCartOpen]=useState(false); const [checkoutOpen,setCheckoutOpen]=useState(false); const [toast,setToast]=useState(''); const [saved,setSaved]=useState<string[]>([]); const [view,setView]=useState<'shop'|'track'>('shop'); const [order,setOrder]=useState<{number:string;status:string;name:string}|null>(null);
 useEffect(()=>{let active=true;fetch('/api/specials',{cache:'no-store'}).then(r=>r.json()).then(data=>{if(active&&data.source==='supabase'&&Array.isArray(data.products)&&data.products.length)setProducts(data.products);}).catch(()=>{});return()=>{active=false}},[]);
 useEffect(()=>{try{const c=localStorage.getItem('freshcart-cart');if(c)setCart(JSON.parse(c));const s=localStorage.getItem('freshcart-saved');if(s)setSaved(JSON.parse(s));const o=localStorage.getItem('freshcart-order');if(o)setOrder(JSON.parse(o));}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(hydrated){localStorage.setItem('freshcart-cart',JSON.stringify(cart));localStorage.setItem('freshcart-saved',JSON.stringify(saved));}},[cart,saved,hydrated]);
 const filtered=useMemo(()=>products.filter(p=>(category==='All groceries'||p.category===category)&&(p.name+' '+p.category+' '+p.desc).toLowerCase().includes(query.toLowerCase())),[category,query,products]);
 const count=cart.reduce((s,i)=>s+i.quantity,0), subtotal=cart.reduce((s,i)=>s+i.price*i.quantity,0), delivery=subtotal===0||subtotal>=350?0:35, total=subtotal+delivery, remaining=Math.max(0,350-subtotal);
 const add=(p:Product)=>{if(p.inStock===false){setToast(`${p.name} is sold out right now.`);setTimeout(()=>setToast(''),2500);return;}setCart(old=>{const found=old.find(i=>i.id===p.id);return found?old.map(i=>i.id===p.id?{...i,quantity:i.quantity+1}:i):[...old,{...p,quantity:1}]});setToast(`${p.name} added to your basket`);setTimeout(()=>setToast(''),2200)};
 const qty=(id:string,n:number)=>setCart(old=>n<=0?old.filter(i=>i.id!==id):old.map(i=>i.id===id?{...i,quantity:n}:i));
 const toggleSave=(id:string)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const placeOrder=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{let accessToken:string|undefined;try{const auth=createBrowserSupabaseClient();accessToken=(await auth.auth.getSession()).data.session?.access_token;}catch{}const result=await createCheckoutOrder({customerName:String(fd.get('name')||''),customerPhone:String(fd.get('phone')||''),customerEmail:String(fd.get('email')||'')||undefined,deliveryAddress:String(fd.get('address')||''),deliveryNotes:String(fd.get('notes')||'')||undefined,items:cart.map(i=>({productSlug:i.slug,quantity:i.quantity}))},accessToken);if(!result.success)throw new Error(result.error);if(!result.redirectUrl)throw new Error('The secure payment page was not returned. Please try again.');localStorage.setItem('freshcart-pending-order',JSON.stringify({id:result.orderId,number:result.orderNumber,total:result.totalAmount}));window.location.assign(result.redirectUrl);}catch(err:any){setToast(err?.message||'We could not start checkout.');setTimeout(()=>setToast(''),4500)}}
 return <main>
  <div className="announcement"><span>✦</span> Fresh finds, fair prices. <b>Free delivery on orders over R350</b><span>✦</span></div>
  <header className="header wrap"><a className="brand" href="#top" onClick={()=>setView('shop')}><span className="brand-mark"><Leaf size={24}/></span><span>fresh<span className="brand-accent">cart</span><small>GOOD FOOD. GOOD MOOD.</small></span></a><div className="search"><Search size={19}/><input aria-label="Search groceries" placeholder="Search fruit, veggies, pantry essentials..." value={query} onChange={e=>{setQuery(e.target.value);setView('shop')}}/><kbd>⌘ K</kbd></div><div className="header-actions"><a className="account-link" href="/account">Account</a><button className="location-btn" onClick={()=>document.getElementById('delivery-address')?.scrollIntoView({behavior:'smooth'})}><MapPin size={19}/><span><small>Delivering to</small><b>Your neighbourhood</b></span><ChevronDown size={15}/></button><button className="basket-btn" onClick={()=>setCartOpen(true)} aria-label="Open basket"><ShoppingBasket size={21}/><span>Basket</span>{count>0&&<i>{count}</i>}</button></div></header>
  <nav className="nav wrap"><button className={view==='shop'?'active':''} onClick={()=>setView('shop')}>Shop all</button><button onClick={()=>{setCategory('Fruit & Veg');setView('shop')}}>Fruit & veg</button><button onClick={()=>{setCategory('Produce Boxes');setView('shop')}}>Family produce boxes</button><button onClick={()=>{setCategory('Pantry');setView('shop')}}>Pantry staples</button><button onClick={()=>setView('track')}>Track my order</button><span className="nav-note"><span className="live-dot"/> Freshness guaranteed</span></nav>
  {view==='shop'?<>
   <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span/> YOUR LOCAL MARKET, ONLINE</div><h1>Good food.<br/><em>Right to your door.</em></h1><p>Fill your fridge with fresh produce, everyday essentials and little things that make home feel like home.</p><div className="hero-buttons"><button className="primary" onClick={()=>{document.getElementById('products')?.scrollIntoView({behavior:'smooth'});}}>Shop fresh picks <ArrowRight size={18}/></button><button className="text-button" onClick={()=>{setCategory('Produce Boxes');document.getElementById('products')?.scrollIntoView({behavior:'smooth'});}}>Explore family boxes</button></div><div className="hero-proof"><div className="avatars"><span>👩🏽</span><span>👨🏾</span><span>👩🏻</span></div><div><b>Freshness you can feel good about</b><small>Carefully picked. Thoughtfully packed.</small></div></div></div><div className="hero-art"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="produce-bowl">🥑🍊🥕<br/>🥬🍅🍌</div><div className="floating-note note-top"><span>🌱</span><div><b>Fresh daily</b><small>Picked with care</small></div></div><div className="floating-note note-bottom"><span className="rating">★</span><div><b>Local goodness</b><small>From our market to you</small></div></div><div className="sunburst">GOOD<br/>FOOD!</div></div></section>
   <section className="benefits wrap"><div><span className="benefit-icon green"><Truck size={21}/></span><p><b>Easy delivery</b><small>To your doorstep</small></p></div><div><span className="benefit-icon yellow"><Leaf size={21}/></span><p><b>Freshness first</b><small>Picked with care</small></p></div><div><span className="benefit-icon peach"><ShieldCheck size={21}/></span><p><b>Fair prices</b><small>Good value every day</small></p></div><div><span className="benefit-icon blue"><Clock3 size={21}/></span><p><b>Shop anytime</b><small>Your market, 24/7</small></p></div></section>
   <section className="category-section wrap"><div className="section-heading"><div><span className="eyebrow">A LITTLE BIT OF EVERYTHING</span><h2>What are we shopping for?</h2></div><button className="text-button" onClick={()=>setCategory('All groceries')}>View all <ArrowRight size={16}/></button></div><div className="category-row">{CATEGORIES.map(c=><button key={c.name} className={'category-pill '+(category===c.name?'selected':'')} onClick={()=>setCategory(c.name)}><span>{c.emoji}</span>{c.name}<ArrowRight size={14}/></button>)}</div></section>
   <section className="products-section wrap" id="products"><div className="section-heading"><div><span className="eyebrow">GOOD THINGS, PICKED FOR YOU</span><h2>{query?`Results for “${query}”`:category==='All groceries'?'Today’s fresh picks':category}</h2><p className="muted">Everyday favourites, seasonal finds and prices worth smiling about.</p></div><div className="product-count">{filtered.length} products <span>↗</span></div></div>{filtered.length?<div className="product-grid">{filtered.map(p=><article className="product-card" key={p.id}><div className="product-image" style={{background:p.color}}>{p.imageUrl?<img className="product-photo" src={p.imageUrl} alt={p.name} loading="lazy"/>:<span className="product-emoji">{p.emoji}</span>}{p.tag&&!p.isSpecial&&<span className="product-tag">{p.tag}</span>}{p.inStock===false&&<span className="sold-out-badge">SOLD OUT</span>}<button className={'save-btn '+(saved.includes(p.id)?'saved':'')} onClick={()=>toggleSave(p.id)} aria-label="Save product"><Heart size={17} fill={saved.includes(p.id)?'currentColor':'none'}/></button></div><div className="product-info"><span className="product-category">{p.category}</span><h3>{p.name}</h3><p>{p.desc}</p><div className="product-bottom"><div><b>{money(p.price)}</b><small>{p.unit}</small></div><button className="add-btn" disabled={p.inStock===false} onClick={()=>add(p)} aria-label={p.inStock===false?`${p.name} sold out`:`Add ${p.name}`}>{p.inStock===false?'Sold out':<Plus size={20}/>}</button></div></div></article>)}</div>:<div className="empty-search"><span>🧺</span><h3>No groceries found just yet</h3><p>Try another search or browse all of our fresh picks.</p><button className="primary" onClick={()=>{setQuery('');setCategory('All groceries')}}>Show all groceries</button></div>}</section>
   <section className="family-banner wrap"><div className="family-illustration">🥔 🥕 🥬<br/>🍅 🎃 🧅</div><div><span className="eyebrow">MADE FOR THE FAMILY TABLE</span><h2>Sunday lunch? <em>Sorted.</em></h2><p>Our family produce boxes bring the good stuff together in one easy bundle. Less planning, more gathering around the table.</p><button className="primary" onClick={()=>{setCategory('Produce Boxes');document.getElementById('products')?.scrollIntoView({behavior:'smooth'})}}>Shop produce boxes <ArrowRight size={18}/></button></div><div className="banner-sticker">MORE IN<br/>EVERY BOX <span>♥</span></div></section>
   <section className="newsletter wrap"><div><span className="eyebrow">A FRESH LITTLE NOTE</span><h2>Good things are growing.</h2><p>New arrivals, seasonal picks and market specials — straight to your inbox.</p></div><form onSubmit={e=>{e.preventDefault();setToast('You’re on the list — thanks for joining!');setTimeout(()=>setToast(''),3000);(e.currentTarget as HTMLFormElement).reset()}}><input type="email" required placeholder="Your email address" aria-label="Your email address"/><button className="primary">Count me in <ArrowRight size={17}/></button></form></section>
  </>:<section className="tracking wrap"><div className="eyebrow">YOUR ORDER, AT A GLANCE</div><h1>Let’s see where your <em>good things are.</em></h1><p className="muted">Your latest order updates, all in one place.</p>{order?<div className="track-card"><div className="track-top"><span className="track-check"><CheckCircle2 size={25}/></span><div><small>ORDER NUMBER</small><h2>{order.number}</h2></div><span className="status-chip">{order.status}</span></div><div className="timeline"><div className="timeline-step done"><span>✓</span><b>Order received</b><small>We have your order, {order.name}.</small></div><div className="timeline-step"><span>2</span><b>Being prepared</b><small>Your groceries are being picked.</small></div><div className="timeline-step"><span>3</span><b>Out for delivery</b><small>On the way to your door.</small></div><div className="timeline-step"><span>4</span><b>Delivered</b><small>Time to enjoy the good stuff.</small></div></div><p className="demo-note">Demo tracking: live courier updates connect when the backend is configured.</p><button className="primary" onClick={()=>setView('shop')}>Continue shopping <ArrowRight size={17}/></button></div>:<div className="no-order"><span>📦</span><h2>No recent order to track</h2><p>Once you place an order, you’ll find its progress here.</p><button className="primary" onClick={()=>setView('shop')}>Start shopping <ArrowRight size={17}/></button></div>}</section>}
  <footer className="footer"><div className="wrap footer-main"><div className="footer-brand"><a className="brand" href="#top" onClick={()=>setView('shop')}><span className="brand-mark"><Leaf size={24}/></span><span>fresh<span className="brand-accent">cart</span><small>GOOD FOOD. GOOD MOOD.</small></span></a><p>Your neighbourhood grocery shop, made a little easier. Fresh finds and everyday essentials, delivered with care.</p></div><div><b>Explore</b><button onClick={()=>{setView('shop');setCategory('Fruit & Veg')}}>Fruit & veg</button><button onClick={()=>{setView('shop');setCategory('Produce Boxes')}}>Produce boxes</button><button onClick={()=>{setView('shop');setCategory('Pantry')}}>Pantry essentials</button></div><div><b>Need a hand?</b><a href="mailto:hello@freshcart.example">Contact our team</a><button onClick={()=>setView('track')}>Track an order</button><button onClick={()=>setCartOpen(true)}>Your basket</button></div><div id="delivery-address"><b>Delivery, made simple</b><p><MapPin size={16}/> Your neighbourhood</p><p><Clock3 size={16}/> Delivery slots confirmed at checkout</p><p><ShieldCheck size={16}/> Secure checkout coming soon</p></div></div><div className="wrap footer-bottom"><span>© 2026 FreshCart. Made for the love of good food.</span><span>Fresh choices. Happy homes. <span className="heart">♥</span></span></div></footer>
  {cartOpen&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setCartOpen(false)}}><aside className="cart-drawer"><div className="drawer-head"><div><span className="eyebrow">YOUR GOOD STUFF</span><h2>Your basket <span>({count})</span></h2></div><button className="close-btn" onClick={()=>setCartOpen(false)} aria-label="Close basket"><X/></button></div>{cart.length===0?<div className="cart-empty"><span>🧺</span><h3>Your basket is taking a little break.</h3><p>Add a few fresh favourites and we’ll keep them right here.</p><button className="primary" onClick={()=>setCartOpen(false)}>Find something fresh</button></div>:<><div className="delivery-progress"><div className="progress-copy">{remaining>0?<>You’re <b>{money(remaining)}</b> away from free delivery</>:<><b>You unlocked free delivery!</b> 🎉</>}</div><div className="progress-track"><span style={{width:`${Math.min(100,subtotal/350*100)}%`}}/></div></div><div className="cart-items">{cart.map(i=><div className="cart-item" key={i.id}><div className="cart-item-img" style={{background:i.color}}>{i.emoji}</div><div className="cart-item-info"><b>{i.name}</b><small>{i.unit}</small><strong>{money(i.price*i.quantity)}</strong><div className="quantity"><button onClick={()=>qty(i.id,i.quantity-1)} aria-label="Decrease quantity"><Minus size={14}/></button><span>{i.quantity}</span><button onClick={()=>qty(i.id,i.quantity+1)} aria-label="Increase quantity"><Plus size={14}/></button></div></div><button className="remove-btn" onClick={()=>qty(i.id,0)} aria-label="Remove item"><X size={16}/></button></div>)}</div><div className="cart-summary"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Delivery</span><b>{delivery===0?'FREE':money(delivery)}</b></div><div className="summary-total"><span>Total</span><b>{money(total)}</b></div><button className="primary checkout-btn" onClick={()=>{setCartOpen(false);setCheckoutOpen(true)}}>Continue to checkout <ArrowRight size={18}/></button><p><ShieldCheck size={15}/> Your details stay private and secure.</p></div></>}</aside></div>}
  {checkoutOpen&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setCheckoutOpen(false)}}><section className="checkout-modal"><div className="drawer-head"><div><span className="eyebrow">ALMOST AT YOUR DOOR</span><h2>Delivery details</h2></div><button className="close-btn" onClick={()=>setCheckoutOpen(false)} aria-label="Close checkout"><X/></button></div><form className="checkout-form" onSubmit={placeOrder}><label>Full name<input name="name" required placeholder="e.g. Sam Mokoena"/></label><label>Phone number<input name="phone" required type="tel" placeholder="e.g. 071 234 5678"/></label><label>Email address <span>(optional)</span><input name="email" type="email" placeholder="you@example.com"/></label><label>Delivery address<textarea id="delivery-address-input" name="address" required placeholder="Street address, suburb, city" rows={3}/></label><label>Delivery notes <span>(optional)</span><textarea name="notes" placeholder="Gate code, landmarks or anything we should know" rows={2}/></label><div className="checkout-total"><span>Order total <small>({count} items · {delivery===0?'free delivery':money(delivery)+' delivery'})</small></span><b>{money(total)}</b></div><div className="demo-warning">Order details will be saved securely to the FreshCart database. Payment integration can be enabled separately when your gateway credentials are configured.</div><button className="primary checkout-btn" type="submit">Place order <ArrowRight size={18}/></button></form></section></div>}
  {toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}
  <button className="mobile-basket" onClick={()=>setCartOpen(true)}><ShoppingBasket size={19}/> Basket {count>0&&<span>{count}</span>}<b>{money(total)}</b></button>
 </main>
}
